<?php

namespace Container4Rijt5i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A1oNo1pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a1oNo1p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a1oNo1p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'employe' => ['privates', '.errored..service_locator.a1oNo1p.App\\Entity\\Employe', NULL, 'Cannot autowire service ".service_locator.a1oNo1p": it references class "App\\Entity\\Employe" but no such service exists.'],
            'employeRepository' => ['privates', 'App\\Repository\\EmployeRepository', 'getEmployeRepositoryService', true],
        ], [
            'employe' => 'App\\Entity\\Employe',
            'employeRepository' => 'App\\Repository\\EmployeRepository',
        ]);
    }
}
