<?php

namespace Container4Rijt5i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_42HSvo9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.42HSvo9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.42HSvo9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'congeRepository' => ['privates', 'App\\Repository\\CongeRepository', 'getCongeRepositoryService', true],
        ], [
            'congeRepository' => 'App\\Repository\\CongeRepository',
        ]);
    }
}
