<?php

namespace Container4Rijt5i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UPED6PlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UPED6Pl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UPED6Pl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'conge' => ['privates', '.errored..service_locator.UPED6Pl.App\\Entity\\Conge', NULL, 'Cannot autowire service ".service_locator.UPED6Pl": it references class "App\\Entity\\Conge" but no such service exists.'],
        ], [
            'conge' => 'App\\Entity\\Conge',
        ]);
    }
}
