<?php

namespace Container4Rijt5i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6NQjcMFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6NQjcMF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6NQjcMF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'conge' => ['privates', '.errored..service_locator.6NQjcMF.App\\Entity\\Conge', NULL, 'Cannot autowire service ".service_locator.6NQjcMF": it references class "App\\Entity\\Conge" but no such service exists.'],
            'congeRepository' => ['privates', 'App\\Repository\\CongeRepository', 'getCongeRepositoryService', true],
        ], [
            'conge' => 'App\\Entity\\Conge',
            'congeRepository' => 'App\\Repository\\CongeRepository',
        ]);
    }
}
