<?php

namespace Container4Rijt5i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticle2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S51ENsP.App\Entity\Article' shared service.
     *
     * @return \App\Entity\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.S51ENsP": it references class "App\\Entity\\Article" but no such service exists.');
    }
}
