<?php

namespace Container4Rijt5i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCongeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6NQjcMF.App\Entity\Conge' shared service.
     *
     * @return \App\Entity\Conge
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6NQjcMF": it references class "App\\Entity\\Conge" but no such service exists.');
    }
}
