<?php

namespace Container4Rijt5i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSujet2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XpezDR2.App\Entity\Sujet' shared service.
     *
     * @return \App\Entity\Sujet
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.XpezDR2": it references class "App\\Entity\\Sujet" but no such service exists.');
    }
}
