<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4Rijt5i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4Rijt5i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4Rijt5i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4Rijt5i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4Rijt5i\App_KernelDevDebugContainer([
    'container.build_hash' => '4Rijt5i',
    'container.build_id' => '24e675bd',
    'container.build_time' => 1676901340,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4Rijt5i');
